### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by Slx87** [ekknod/scripthial#30]
please, scripthial offets update pls. thanks..

**Comment by Slx87** [comment]
no man, CS GO new update also made offsets different. With -insecure, it still didn't work. There is a problem with offsets, it needs to be updated

**Comment by ksoju** [comment]
I use the same offsets on a different project... don't @ me.

**Comment by ksoju** [comment]
If you do not understand programming, then no. You learn offsets when you learn coding. After you learn coding, you learn that most software like csgo is released as binaries. You can't read binaries without reverse engineering the binaries. When you RE the binaries you are able to get offsets/signatures. It is hard to do this if you don't have the fundamentals. 

Most people resort to running tools like hazedumper and pasting in the offsets/netvars to source code provided they have enough understanding of the source code. The barrier for most people is their lack of coding knowledge breaks functionality due to their mistakes. It is still easier to paste than learn RE.

Regarding your issue, the code failing is specific to scripthial only as offsets were unaffected in G37OBS. That is why I do not agree it is an offset issue. You'd be wasting your time (but not really if you genuinely wanting to learn to do this on your own). There's lot's of online resources for learning. So to be clear, no I am not going to tell you how to change offsets. I am also not a resource to @ when you are stuck. 

I can't speak for the others but my priority is not updating older projects. Furthermore, there are many alternatives out there that don't involve learning to code which I suggest is your optimal choice. It is my understanding the point of releasing scripthial was as a base to modify. Practically all ekknod's repos are not for regular consumption but as a starting point for developing your own projects. Any bugs inherited in your usage of open source code is again your responsibility and not any one particular dev.
